package com.shuyu.video.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.shuyu.video.model.AppPayInfo;
import com.shuyu.video.model.AppStore;
import com.shuyu.video.model.Payment;

import com.shuyu.video.db.dao.AppPayInfoDao;
import com.shuyu.video.db.dao.AppStoreDao;
import com.shuyu.video.db.dao.PaymentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appPayInfoDaoConfig;
    private final DaoConfig appStoreDaoConfig;
    private final DaoConfig paymentDaoConfig;

    private final AppPayInfoDao appPayInfoDao;
    private final AppStoreDao appStoreDao;
    private final PaymentDao paymentDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appPayInfoDaoConfig = daoConfigMap.get(AppPayInfoDao.class).clone();
        appPayInfoDaoConfig.initIdentityScope(type);

        appStoreDaoConfig = daoConfigMap.get(AppStoreDao.class).clone();
        appStoreDaoConfig.initIdentityScope(type);

        paymentDaoConfig = daoConfigMap.get(PaymentDao.class).clone();
        paymentDaoConfig.initIdentityScope(type);

        appPayInfoDao = new AppPayInfoDao(appPayInfoDaoConfig, this);
        appStoreDao = new AppStoreDao(appStoreDaoConfig, this);
        paymentDao = new PaymentDao(paymentDaoConfig, this);

        registerDao(AppPayInfo.class, appPayInfoDao);
        registerDao(AppStore.class, appStoreDao);
        registerDao(Payment.class, paymentDao);
    }
    
    public void clear() {
        appPayInfoDaoConfig.getIdentityScope().clear();
        appStoreDaoConfig.getIdentityScope().clear();
        paymentDaoConfig.getIdentityScope().clear();
    }

    public AppPayInfoDao getAppPayInfoDao() {
        return appPayInfoDao;
    }

    public AppStoreDao getAppStoreDao() {
        return appStoreDao;
    }

    public PaymentDao getPaymentDao() {
        return paymentDao;
    }

}
